// <auto-generated />
namespace Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v2createproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2createproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202211281030105_v2 - create product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
